"""Generate a decimal-aligned LaTeX comparison table from recorded experiments.

Writes a tabular environment to stdout; the document must load dcolumn.
Uses only the Python standard library and does not modify the manuscript.
"""

import argparse
import json
import sys
from pathlib import Path


# Keep this standalone script usable without installing the analysis package.
sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))
from atom_reloading_analysis.environments import normalize_environment


METHODS = (
    ("baseline", r"Baseline~\cite{cite:3000_coherent}"),
    ("proposed", "Proposed"),
    ("greedy", "Greedy"),
    ("simple_greedy", "Simple greedy"),
    ("mip_glpk", "MIP (GLPK)"),
    ("mip_scip", "MIP (SCIP)"),
    ("row_by_row", "Row-by-row"),
)
ROW_BY_ROW_RESULTS = Path("additional_row_by_row_20260927/results_row_by_row.json")


def format_cells(data, environment, n, time_digits=3):
    rows = [r for r in data["results"]
            if normalize_environment(r["environment"]) == normalize_environment(environment)
            and r["n"] == n]
    if len(rows) > 1:
        raise ValueError(f"Duplicate results for {environment}, n={n}")
    if not rows or rows[0]["status"] != "completed":
        return (r"\multicolumn{2}{c}{---} & \multicolumn{1}{c}{---}"
                r" & \multicolumn{1}{c}{---}")
    row = rows[0]
    if row["num_trials_done"] != data["num_trials"]:
        raise ValueError("Completed result does not contain all requested trials")
    if data["num_iterations"] <= 0:
        raise ValueError("num_iterations must be positive")
    if (data["planning_time_scope"] != "plan call only"
            or data["runtime_time_scope"] != "sum of plan calls per trial including burn-in"):
        raise ValueError("Expected planning-call-only timing, including burn-in")
    # Apply the same four decimal places to every filling rate and sample SD.
    return (f'{row["filling_rate_percent"]:.4f} & '
            f'{row["filling_rate_percent_std"]:.4f} & '
            f'{row["runtime_ms"] / data["num_iterations"]:.{time_digits}f} & '
            f'{row["max_planning_wall_ms"]:.{time_digits}f}')


def generate_table(results_dir, n=3, row_by_row_results=None):
    data = {key: json.loads((results_dir / f"results_{key}.json").read_text())
            for key, _ in METHODS if key != "row_by_row"}
    row_path = row_by_row_results or results_dir / ROW_BY_ROW_RESULTS
    if row_by_row_results is not None or row_path.exists():
        data["row_by_row"] = json.loads(row_path.read_text())
    cells = {}
    widths = [1, 1, 1, 1]
    for environment in ("Low noise", "High noise"):
        for key, experiment in data.items():
            value = format_cells(experiment, environment, n,
                                 time_digits=4 if key == "row_by_row" else 3)
            cells[environment, key] = value
            if not value.startswith(r"\multicolumn"):
                widths = [max(width, len(number.strip().split(".")[0]))
                          for width, number in zip(widths, value.split("&"))]
    columns = [f"D{{.}}{{.}}{{{width}.4}}" for width in widths]
    lines = [
        r"% Generated by analysis/filling_rate_table.py; requires \usepackage{dcolumn}.",
        r"\begin{tabular}{l " + columns[0] + r"@{${}\pm{}$}"
        + " ".join(columns[1:]) + "}",
        r"  \toprule",
        r"  Method & \multicolumn{2}{c}{$F$ (\%)} & \multicolumn{1}{c}{Time/step (ms)} & \multicolumn{1}{c}{Worst plan (ms)} \\",
    ]
    for environment, title, p in (("Low noise", "Low-noise", "0.004"),
                                  ("High noise", "High-noise", "0.020")):
        lines += [r"  \midrule",
                  rf"  \multicolumn{{5}}{{l}}{{\textit{{{title} case ($p = {p}$)}}}} \\"]
        for key, label in METHODS:
            if key in data:
                lines.append(f"  {label} & {cells[environment, key]} " + r"\\")
    lines += [r"  \botrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-dir", type=Path,
                        default=Path(__file__).resolve().parents[1] / "results")
    parser.add_argument("--n", type=int, default=3)
    parser.add_argument("--row-by-row-results", type=Path,
                        help="Optional separate row-by-row experiment JSON")
    args = parser.parse_args()
    if args.n < 1:
        parser.error("--n must be positive")
    print(generate_table(args.results_dir, args.n, args.row_by_row_results), end="")


if __name__ == "__main__":
    main()
